# Site settings
title: Identihub 
description: Open Source brand & assets management software

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://identihub.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 1
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-multiple-languages-plugin]
languages: ["en", "sq", "it"]
# Build settings
